import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import vite from "../public/Vitejs-logo.png"
import js from "../public/js.png"
import py from "../public/py.png"
import redux from "../public/redux.png"
import ts from "../public/ts.png"
import pf from "../public/pf.png"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={(!darkMode) ? "dark" : ""}>
      <Head>
        <title>Rudra Bassi - Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Rudra Bassi</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-red-500 text- to-red-600 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-red-400 md:text-6xl">
              Rudra Bassi
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              React Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Alone side my Computer Science and Science degree I taught
              myself from the fundamentals of web development to building an
              eCommerce website from scratch.
              <br />
              <b>Join me in my journey to become
                a full stack dev & app developer!</b>
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Image src={vite} width={"50px"} height={"50px"} alt="alt" />
              <Image src={js} width={"50px"} height={"50px"} alt="alt" />
              <Image src={redux} width={"50px"} height={"50px"} alt="alt" />
              <Image src={py} width={"50px"} height={"50px"} alt="alt" />
              <Image src={ts} width={"50px"} height={"50px"} alt="alt" />
            </div>
            <div className="mx-auto bg-gradient-to-b from-blue-900 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={pf} alt="good" className="object-fill" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Skills</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Skilled in React for building dynamic and responsive web applications, with experience in
              JavaScript, HTML5, and CSS3. <span className="text-red-500 font-semibold"> Eager to expand knowledge </span>in backend development
              (Node.js, firebase, AWS) and mobile app development using React Native.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} alt="GOOD" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Relevant University Skills
              </h3>
              <p className="py-2">
                I can carry over what my Computer Science degree taught me to find more simplier ways to find a solution.
              </p>
              <h4 className="py-4 text-red-600">For example:</h4>
              <p className="text-gray-800 py-1">Object Orientied Programming</p>
              <p className="text-gray-800 py-1">SOLID principles</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Advanced Data Structures</p>
              <p className="text-gray-800 py-1">Problem-Solving and Algorithms</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} alt="good" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Self taught Skills
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Lets make it a
                reality.
              </p>
              <br />
              <h4 className="py-4 text-red-600">My relevant skills are:</h4>
              <p className="text-gray-800 py-1">HTML, CSS, JS</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Redux | Tailwind | Router-Dom</p>
              <p className="text-gray-800 py-1">Reusabile components and custom hooks</p>
              <p className="text-gray-800 py-1">json server auth</p>
              <p className="text-gray-800 py-1">Reading documentation</p>
              <p className="text-gray-800 py-1">Learning from articles</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} alt="good" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Character</h3>
              <p className="py-2">
                What kind of person I am
              </p>
              <br />
              <br />
              <h4 className="py-4 text-red-600">Traits</h4>
              <p className="text-gray-800 py-1">Want to learn wide-variety of skills</p>
              <p className="text-gray-800 py-1">Dedicated</p>
              <p className="text-gray-800 py-1">Problem-solver</p>
              <p className="text-gray-800 py-1">Find multiple solutions</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Front-end React developer with expertise in creating dynamic, responsive user interfaces. Proficient in using
              modern JavaScript frameworks to deliver seamless user experiences across web and mobile platforms.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Below are some of the projects showcasing my ability to build interactive, user-focused applications using
              React and modern front-end technologies.            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 bg-slate-200 flex-row  rounded-md justify-between">
              <div className="pt-0  pb-3 my-1 flex-1 px-2">
                <div className="flex flex-row">
                  <h1 className="px-4 py-2 pt-4 text-xl">eCommerce Website</h1>
                  <h1 className="px-4 py-2 pt-4 text-xl text-gray-400 hover:underline hover:cursor-pointer"><a href="https://github.com/xpikachuzz/course-shop" target="_blank" rel="noreferrer" >{"<git />"}</a></h1>
                </div>
                <div className="px-4 text-sm">
                  <p className="font-bold my-1">Skills:</p>
                  From this I learnt a library I didnt know I needed, Redux, it simplified global state mangement
                  and removed the need for irrelevant prop drillings.
                  I also learnt how to create <b>google sign in</b>. And fetched data from local json server.
                  <br />
                  <p className="font-bold my-1">Improvements:</p>
                  Learn how to move local json server to backend and use it to store registered emails and product
                  details.
                </div>
              </div>
              <div className="pb-2 px-2">
                <a href="https://course-shopy.netlify.app" target="_blank" rel="noreferrer">
                  <Image
                    className="w-full rounded-b h-full object-cover"
                    src={web3}
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    alt="site_cover"
                  />
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1 h-full bg-slate-200  rounded-md overflow-hidden justify-between">
              <div className="pt-0 px-2 pb-3 my-1">
                <div className="flex flex-row">
                  <h1 className="px-4 py-2 pt-4 text-xl">Anime Search</h1>
                  <h1 className="px-4 py-2 pt-4 text-xl text-gray-400 hover:underline hover:cursor-pointer"><a href="https://github.com/xpikachuzz/absCinema" target="_blank" rel="noreferrer" >{"<git />"}</a></h1>
                </div>
                <div className="px-4 text-sm">
                  <p className="font-bold my-1">Skills:</p>
                  Handling filters, states, public api calls and searches at the same time.
                  <br />
                  <p className="font-bold my-1">Improvements:</p>
                  Display trailers (available through the api), improve the design and adding a dark mode.
                </div>
              </div>
              <div className="w-full h-full px-2 pb-2">
                <a href="https://animemate.netlify.app" target="_blank" rel="noreferrer">
                  <Image
                    className="w-full rounded-b h-full object-cover"
                    src={web1}
                    width={"100%"}
                    height={"100%"}
                    layout="responsive"
                    alt="site_cover"
                  />
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1 h-full bg-slate-200  rounded-md overflow-hidden justify-between">
              <div className="pt-0 px-2 pb-2 my-1">
                <div className="pt-0 px-2 pb-3 my-1 ">
                  <div className="flex flex-row">
                    <h1 className="px-4 py-2 pt-4 text-xl">To-Do Task</h1>
                    <h1 className="px-4 py-2 pt-4 text-xl text-gray-400 hover:underline hover:cursor-pointer"><a href="https://github.com/xpikachuzz/task-mate" target="_blank" rel="noreferrer" >{"<git />"}</a></h1>
                  </div>
                  <div className="px-4 text-sm">
                    <p className="font-bold my-1">Skills:</p>
                    This is my earlier project. A simple to-do list where the tasks are editable.
                    It also lets you log-in to google
                    <br />
                    <p className="font-bold my-1">Improvements:</p>
                    Learn the <code>react.email</code> library to email the tasks to yourself after
                    you logged in-to google.
                  </div>
                </div>
                <div className="w-full h-full">
                  <a href="https://task-maty.netlify.app" target="_blank" rel="noreferrer">
                    <Image
                      className="w-full rounded-b h-full object-cover"
                      src={web2}
                      width={"100%"}
                      height={"100%"}
                      layout="responsive"
                      alt="site_cover"
                    />
                  </a>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1 h-full bg-slate-200  rounded-md overflow-hidden justify-between">
              <div className="pt-0 px-2 pb-3 my-1">
                <div className="flex flex-row">
                  <h1 className="px-4 py-2 pt-4 text-xl">Chess OOP</h1>
                  <h1 className="px-4 py-2 pt-4 text-xl text-gray-400 hover:underline hover:cursor-pointer"><a href="https://github.com/xpikachuzz/chessy" target="_blank" rel="noreferrer" >{"<git />"}</a></h1>
                </div>
                <div className="px-4 text-sm">
                  <p className="font-bold my-1">Skills:</p>
                  <b>I enjoyed discovering how react (especially the useState) lends itself to OOP, you return a new
                    object and set it as the newState then it refreshes.</b>
                  <br />
                  Object Orientied Programming. Reusable classes. I can add any piece anywhere on the
                  board and the game will still work. I can create customer pieces limited consequences.
                  <br />
                  <p className="font-bold my-1">Improvements:</p>
                  Add easy to add key features such as 2 steps first a pawns first move. Add animations
                  for when pieces move. Show killed pieces.
                  Modularize the process of finding possible moves.
                </div>
                <div className="w-full h-full mt-4">
                  <a href="https://chess-maty.netlify.app" target="_blank" rel="noreferrer">
                    <Image
                      className="w-full rounded-b h-full object-cover"
                      src={web4}
                      width={"100%"}
                      height={"100%"}
                      layout="responsive"
                      alt="site_cover"
                    />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div >
  );
}
